# ---------------------------------------------------------------------------- #
# Project Info
#   Default values shown. Learn more about these options by running
#   `fontcustom help` or visit <http://fontcustom.com>.
# ---------------------------------------------------------------------------- #

font_name: guicicon
css_prefix: guicicon--
no_hash: true
debug: true


# ---------------------------------------------------------------------------- #
# Project Paths
#   Relative paths are expanded from PROJECT_ROOT (default: working directory).
#   INPUT and OUTPUT can be assigned as hashes instead of a strings.
#   The OUPUT hash can route custom templates according to their filename.
# ---------------------------------------------------------------------------- #

input:
 vectors: app/assets/images/svg
 templates: config/templates

output:
 fonts: app/assets/fonts
 css: app/assets/stylesheets/base
 _iconography.html.haml: app/views/styleguide


# ---------------------------------------------------------------------------- #
# Templates
#   Included in Font Custom:
#     preview, css, scss, scss-rails, bootstrap, bootstrap-scss, bootstrap-ie7,
#     bootstrap-ie7-scss
#   Custom templates should be saved in the INPUT[:templates] directory.
# ---------------------------------------------------------------------------- #

templates: [ _iconography.sass, _iconography.html.haml ]
